WebXDAO/devprotocol.xyz

.github/workflows/deploy.yml, astro.config.mjs
I think this should fix the deployment issue
=> feat: deployment

src/layouts/Default.astro
fixes #9 (Keywords not added since they are now excluded from serp ranking)
=> feat: meta description seo

src/layouts/Default.astro
=> fix: duplicate class

.github/workflows/release.yml
Things added/changed:
- Use the latest version for GitHub actions.
=> feat: Use the latest version for GitHub actions

.gitpod.yml, yarn.lock
- Use Yarn commands instead of NPM commands in the `.gitpod.yml` file.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/89"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Use Yarn commands instead of NPM commands

src/components/Creators/Features.astro, src/components/Creators/Hero.astro, src/pages/creators.astro
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/91"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: features section

src/components/Creators/Features.astro, src/components/Creators/Hero.astro, src/components/Creators/Team.astro, src/pages/creators.astro, tailwind.config.js
Cc @vinzvinci 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/93"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Feat center features

.github/pull_request_template.md
- Update from `master` to `main` branch in the PR template.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/95"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: update from `master` to `main` branch

src/components/Developers/Features.astro
- Fix spelling errors in the Developers/Features page.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/94"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: spelling errors in the Developers/Features page

CONTRIBUTING.md
- Fix the invitation link and improve the wording.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/96"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: invitation link and improve wording

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/other.yml
- Add missing issue forms.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/99"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Add missing issue forms

README.md
- Use Yarn commands in the `README.md` file.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/97"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: use Yarn commands in the `README.md` file

src/components/Creators/Hero.astro
- Update creators page text.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: Update creators text

package.json
- Add license and other fields in the `package.json` file.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/108"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: Add license and other fields in the `package.json` file

src/components/Creators/Hero.astro, src/components/Creators/UseCases.astro, src/pages/creators.astro
fixes #107 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/109"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: use cases section

.github/ISSUE_TEMPLATE/bug_report.yml
- Update the bug report template.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/114"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> chore: update the bug report template

.github/ISSUE_TEMPLATE/feature_request.yml
- Update the CoC link in the feature request template.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/115"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Update CoC link in the feature request template

.github/ISSUE_TEMPLATE/config.yml
- Add contact links in the configuration template.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: add contact links in the configuration template

src/components/Creators/UseCases.astro
- Update the "use-cases" section.
- Spelling typos and missing endline.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Update the "use-cases" section

.github/ISSUE_TEMPLATE/config.yml
- Fix the contact link in the issue template configuration.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: contact link in the issue template configuration

src/components/Creators/StepbyStep.astro
- Improve the "Step by Step" section.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Improve the "Step by Step" section

.github/workflows/first-interaction.yml
Welcome users on the first interaction
Notes (**optional**): An Action that would welcome first interactors
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/126"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: welcome first timers

src/components/Home/SuccessStories.vue
- Fix Vyper Stakes.Social link.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/128"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Vyper Stakes.Social link

src/components/Creators/Hero.astro, src/components/Developers/Hero.astro, src/components/Patrons/Hero.astro, tailwind.config.js
Fixes the content going larger that media
Check live via the netlify preview.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: content larger the media

package-lock.json, src/components/Home/SuccessStories.vue
Improved slider section but adjusting image according to design and reduced white spacing in mobile size.
Closes #63 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Improved slider section

src/layouts/Default.astro
- Fix the meta description.
- This will improve our SEO as well.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/135"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: Meta description

src/components/Global/Navigation.astro, src/layouts/Default.astro
Fixed Navbar and footer in mobile view
Closed #123 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixed Navbar and Footbar - Mobile View

src/components/Global/Navbar.vue
Closes #134 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [Fix]: Launch App Icon in Desktop View

src/components/Developers/Team.astro
- Redirect to their respective profiles for all the team.
- UNTESTED, might not work.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Redirect to their respective profiles for all the team

src/layouts/Default.astro
- Add `og:description`.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add `og:description`

src/components/Creators/Hero.astro, src/components/Developers/Hero.astro, src/components/Global/Navigation.vue, src/components/Patrons/Hero.astro
closes #152 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bug Image fix mobile view 152

.github/PULL_REQUEST_TEMPLATE.md
- Fix contributing guidelines link.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: contributing guidelines link

src/components/Faq/Faq.vue
- Improve FAQ translation wording.
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> docs: improve FAQ translation wording

src/pages/community-partners.astro
Closes #173 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat: Add intlify to the list of community partners

src/pages/community-partners.astro
The background color of cards in community page when using light mode is highly distracting.
- Changed the background color of community partners background color to white when in light mode.
- Added a touch of gray in background color of community partners when in dark mode. 
- Added slight highlight to "visit site" button.
Current design *(light mode)*:
Proposed changes *(light mode)*:
<hr>
Current design *(dark mode)*:
Proposed changes *(dark mode)*:
*   I acknowledge that all my contributions will be made under the …
=> [UPDATE]: Improved the color combination of community partners page in light mode

src/components/Global/Navbar.vue, tailwind.config.js
fixes #162 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: renew brand logo

src/pages/community-partners.astro
- added more margin when in mobile view to remove the cutoff
- Fixes #178 
Current design:
Proposed changes:
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [FIX]: Community partners cutoff

src/components/Faq/lang.csv
- Reordered FAQ
- Closes #182
[Basis](https://github.com/web3community/devprotocol.xyz/issues/182):
New FAQ order:
*(For Everyone)*:
*(Creators)*:
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [UPDATE]: Reorder FAQ

src/components/Faq/Faq.vue
Changes FAQ translate button
Closes #185 
Let me know if any style modification is needed. 
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/186"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix: change translate button

src/pages/community-partners.astro
- Resolved the overflow in button
- fixes #196
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/197"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> FIXED: Community Partners button overflow

src/components/Global/Navbar.vue
As requested by Miyamoto. This is just for the preparation of the DEV Shop, I'll merge this later.
N/A
<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add DEV Shop

src/components/Faq/Faq.vue
closes #214 
<a href="https://gitpod.io/#https://github.com/WebXDAO/devprotocol.xyz/pull/215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> FAQ Page: fix negative margins
